name: Deploy Laravel via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy to Web Server
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, mysqlnd

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader --prefer-dist

      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /home/premium2/domains/ecom1.premiumtouchbd.com/public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env
            .env.example
            tests/
            phpunit.xml
